### ISSUE TITLE
 ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by hyunwhanjoe** [hallamlab/mlLGPR#2]
When running Preprocessing Example 2 in prep_biocyc/DataObject.py line 591 and 604 "X_lst.remove(np.where(colID == dictID[r])[0])" a ValueError occurs when x is not in the list.

**Comment by arbasher** [comment]
Thank you, we resolved the problem!

**Comment by hyunwhanjoe** [comment]
I updated the code but I'm still having the same problem. I currently got it to run by first checking if np.where(colID == dictID[r])[0] is in X_lst then removing it but I'm not sure if this is actually correct.

**Comment by arbasher** [comment]
Can you download these files again from zenodo and rerun example 2: "object.pkl", "pathway_ec.pkl", "reaction_ec.pkl", "ec2pathway.txt", "pathwayfeature.pkl", and "ecfeature.pkl"?!

**Comment by hyunwhanjoe** [comment]
Ah I was running example 2 without "reaction_ec.pkl", "ec2pathway.txt", and "pathwayfeature.pkl". I downloaded the files and it runs without a problem. Thank you for your help.
